security:
  encoders:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    main:
      user_checker: App\Security\UserChecker
      lazy: true
      anonymous: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: app_dossier_index
        username_parameter: _username
        password_parameter: _password
        enable_csrf: false
      logout:
        path: app_logout
        target: app_login
        invalidate_session: true

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/user/verify, roles: IS_AUTHENTICATED_ANONYMOUSLY }
